version: '3.9'

services:
  springboot:
    image: wafalasri/employesproject-backend:1.0
    container_name: employeesproject-backend
    ports:
      - "8081:8081"
    networks:
      - employee-network

  frontend:
    image: wafalasri/employesproject-frontend:1.0
    container_name: employeesproject-frontend
    ports:
      - "4200:80"
    depends_on:
      - springboot
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge